import { Book, Category, User } from './types';

export const categories: Category[] = [
  { id: 'all', name: 'All Books', count: 248, icon: '📚', color: 'bg-blue-100 text-blue-700' },
  { id: 'fiction', name: 'Fiction', count: 89, icon: '📖', color: 'bg-purple-100 text-purple-700' },
  { id: 'science', name: 'Science', count: 56, icon: '🧪', color: 'bg-green-100 text-green-700' },
  { id: 'technology', name: 'Technology', count: 42, icon: '💻', color: 'bg-blue-100 text-blue-700' },
  { id: 'history', name: 'History', count: 38, icon: '🏛️', color: 'bg-yellow-100 text-yellow-700' },
  { id: 'arts', name: 'Arts', count: 23, icon: '🎨', color: 'bg-pink-100 text-pink-700' },
];

export const books: Book[] = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0-7432-7356-5',
    category: 'fiction',
    description: 'A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.',
    coverUrl: 'https://images.pexels.com/photos/1130980/pexels-photo-1130980.jpeg',
    rating: 4.2,
    totalRatings: 1542,
    publishedYear: 1925,
    pages: 180,
    isAvailable: true,
    isFavorite: false,
  },
  {
    id: '2',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '978-0-06-231609-7',
    category: 'history',
    description: 'An exploration of how Homo sapiens became the dominant species and shaped the modern world.',
    coverUrl: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg',
    rating: 4.7,
    totalRatings: 2341,
    publishedYear: 2011,
    pages: 464,
    isAvailable: false,
    dueDate: '2025-01-15',
    isFavorite: true,
    readingProgress: 65,
  },
  {
    id: '3',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    isbn: '978-0-13-235088-4',
    category: 'technology',
    description: 'A handbook of agile software craftsmanship with practical advice for writing maintainable code.',
    coverUrl: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg',
    rating: 4.5,
    totalRatings: 987,
    publishedYear: 2008,
    pages: 464,
    isAvailable: true,
    isFavorite: true,
  },
  {
    id: '4',
    title: 'The Art of War',
    author: 'Sun Tzu',
    isbn: '978-1-59308-017-7',
    category: 'history',
    description: 'Ancient Chinese military treatise that has influenced strategic thinking across cultures.',
    coverUrl: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg',
    rating: 4.1,
    totalRatings: 756,
    publishedYear: -500,
    pages: 96,
    isAvailable: true,
    isFavorite: false,
  },
  {
    id: '5',
    title: 'The Origin of Species',
    author: 'Charles Darwin',
    isbn: '978-0-14-043205-1',
    category: 'science',
    description: 'Groundbreaking work that introduced the theory of evolution through natural selection.',
    coverUrl: 'https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg',
    rating: 4.3,
    totalRatings: 1234,
    publishedYear: 1859,
    pages: 502,
    isAvailable: true,
    isFavorite: false,
  },
  {
    id: '6',
    title: 'The Starry Night: Van Gogh',
    author: 'Vincent van Gogh',
    isbn: '978-0-8109-4738-1',
    category: 'arts',
    description: 'An exploration of one of the most famous paintings in the world and its cultural impact.',
    coverUrl: 'https://images.pexels.com/photos/894156/pexels-photo-894156.jpeg',
    rating: 4.6,
    totalRatings: 432,
    publishedYear: 1889,
    pages: 128,
    isAvailable: false,
    dueDate: '2025-01-22',
    isFavorite: false,
  },
];

export const currentUser: User = {
  id: '1',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@university.edu',
  avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
  booksRead: 47,
  booksCheckedOut: 3,
  favoriteGenre: 'Science Fiction',
  joinDate: '2023-09-01',
};